# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Hl7lens < Formula
  desc "Read, validate, and safely share HL7 v2.x messages"
  homepage "https://github.com/sumvee/hl7lens"
  version "0.2.0"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/sumvee/hl7lens/releases/download/v0.2.0/hl7lens_0.2.0_darwin_amd64.tar.gz"
      sha256 "4ecdfe659af1b2c037b06ab0821eedbf93c59c6fee064b6aa934d8f873a294fc"

      define_method(:install) do
        bin.install "hl7lens"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/sumvee/hl7lens/releases/download/v0.2.0/hl7lens_0.2.0_darwin_arm64.tar.gz"
      sha256 "5599034d49b82c37e733b87246181b42fac0352f603008c822d904f98196d5b8"

      define_method(:install) do
        bin.install "hl7lens"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/sumvee/hl7lens/releases/download/v0.2.0/hl7lens_0.2.0_linux_amd64.tar.gz"
      sha256 "7a256b0708394c2d3eb6cae87198bd8d9071d598b530e16893aef225f714b016"
      define_method(:install) do
        bin.install "hl7lens"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/sumvee/hl7lens/releases/download/v0.2.0/hl7lens_0.2.0_linux_arm64.tar.gz"
      sha256 "61c3e282e9dae8216c55ed948d0834d13025669d299d8f30c484fed231dcba6e"
      define_method(:install) do
        bin.install "hl7lens"
      end
    end
  end

  test do
    system "#{bin}/hl7lens", "--version"
  end
end
