# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Hl7lens < Formula
  desc "Read, validate, and safely share HL7 v2.x messages"
  homepage "https://github.com/sumvee/hl7lens"
  version "0.1.0"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/sumvee/hl7lens/releases/download/v0.1.0/hl7lens_0.1.0_darwin_amd64.tar.gz"
      sha256 "6b085e8e3b5adfe63ae91cbcc5552192fed93c80c862abd4f513305637e8d52d"

      define_method(:install) do
        bin.install "hl7lens"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/sumvee/hl7lens/releases/download/v0.1.0/hl7lens_0.1.0_darwin_arm64.tar.gz"
      sha256 "3cc609ddedbee5e86bccce58c0ef3fd19b5c5e19618aa02fa510371a3d0ffa3b"

      define_method(:install) do
        bin.install "hl7lens"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/sumvee/hl7lens/releases/download/v0.1.0/hl7lens_0.1.0_linux_amd64.tar.gz"
      sha256 "dcaeda9696bd3226693d1f4771b4e84e84ad4694b1d3049fb1cbfe304656c4ca"
      define_method(:install) do
        bin.install "hl7lens"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/sumvee/hl7lens/releases/download/v0.1.0/hl7lens_0.1.0_linux_arm64.tar.gz"
      sha256 "33524043c8dbb034a71718653db2240c0601ddb1b3d76d8da2b76712dfa1e0af"
      define_method(:install) do
        bin.install "hl7lens"
      end
    end
  end

  test do
    system "#{bin}/hl7lens", "--version"
  end
end
