# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Hl7lens < Formula
  desc "Read, validate, and safely share HL7 v2.x messages"
  homepage "https://github.com/sumvee/hl7lens"
  version "0.1.1"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/sumvee/hl7lens/releases/download/v0.1.1/hl7lens_0.1.1_darwin_amd64.tar.gz"
      sha256 "ccb4d2a680fe12eb31f631d6dd9e800b8a2319e20f37ed258bbd104662bae8ad"

      define_method(:install) do
        bin.install "hl7lens"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/sumvee/hl7lens/releases/download/v0.1.1/hl7lens_0.1.1_darwin_arm64.tar.gz"
      sha256 "b8f9404ead630870d14170b09aaab7dc91e0901c163c7ee195abefd50a2cd6b2"

      define_method(:install) do
        bin.install "hl7lens"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/sumvee/hl7lens/releases/download/v0.1.1/hl7lens_0.1.1_linux_amd64.tar.gz"
      sha256 "74a036cfabde537ce083491fc362601bda740a5c0ec50fc04764e682a6d99da5"
      define_method(:install) do
        bin.install "hl7lens"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/sumvee/hl7lens/releases/download/v0.1.1/hl7lens_0.1.1_linux_arm64.tar.gz"
      sha256 "ccc94bf7e6e7dc5b5a79b4766199006435502955a11142ff80e99e017e3e4e47"
      define_method(:install) do
        bin.install "hl7lens"
      end
    end
  end

  test do
    system "#{bin}/hl7lens", "--version"
  end
end
